remote_theme: rundocs/jekyll-rtd-theme
title: Just the Docs
description: A Jekyll theme for documentation

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

color_scheme: dark
